"""Stage 1: create the project's master feature service.

The copy is done here, in two calls, the way `copy_feature_layer_collection()`
does it internally: `createService` with the template's service settings, then
one `addToDefinition` carrying every layer and table. Phase 0b proved that method
`USABLE WITH FIXUPS` with no critical differences, so there is no
publish-from-FGDB fallback. It is ours rather than the library's for one reason:
the library posts each layer's `relationships` verbatim, and a relationship
names its related layer by the *template's* layer id, which AGOL renumbers on
the way in. The Kinetic master (2 relationships) was refused outright with a
400 that named a .NET type and no layer, and the library cannot be told to
strip them. So the layers are posted without their relationships, and
`reapply_relationships` puts them back with the ids remapped by layer name --
which is exactly what Esri's own `clone_items` does. Doing it in two calls also
keeps the item in hand before the call that can fail; the library raised with
the service it had just created lost inside the exception.

The copy strips each layer's `indexes` before applying
the definition, so even a perfect copy arrives without them. The spike reported
83 missing index entries across 18 layers, of which 73 are system-generated names
that could never have matched -- SQL Server primary keys with random suffixes,
spatial indexes scoped to the owning account, editor-tracking indexes renumbered
on creation, and GlobalID indexes recreated with the field. Ten are real:
`build_status_Index` on 9 layers and `I25bore_depth` on 1.

The first live run confirmed the renumbering rather than merely predicting it.
The copy deletes `indexes` from every layer definition
before posting it, and this module drops every single-system-field index, so the
creation request carried *no* GlobalID or editor-tracking index at all -- yet the
copy has them, under names without the template's `I25` prefix. ArcGIS Online
creates them itself from the GlobalID field and the copied editor-tracking
settings. Nothing names an index but the query planner, so nothing is lost.

`build_status_Index` is the one that matters. `build_status` is the field that
*every* view's definition query filters on, so a master without it makes all
seven views table-scan.

Indexes are classified by their **fields**, never by their names. The system names
carry random suffixes and owner ids, and `I25bore_depth` shows that the `I##`
prefix appears on user indexes too, so the name is evidence of nothing in either
direction.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from typing import Any

# AGOL wording when an index of that name is already there. Tolerated rather than
# fatal: the index existing is the outcome this stage wants either way.
_DUPLICATE_MARKERS = ("duplicate", "already exists", "already in use")

APPLIED = "applied"
ALREADY_PRESENT = "already present"
FAILED = "failed"

# What `copy_feature_layer_collection()` carries from the template's service
# properties into `createService`. Its list, verbatim, so the service is created
# exactly as the copy the spike verified created it. Everything else on the
# service (`serviceItemId`, `layers`, the org's own metadata) AGOL sets itself.
SERVICE_PARAMS = (
    "description", "allowGeometryUpdates", "units", "syncEnabled",
    "serviceDescription", "capabilities", "serviceItemId",
    "supportsDisconnectedEditing", "maxRecordCount", "supportsApplyEditsWithGlobalIds",
    "name", "supportedQueryFormats", "xssPreventionInfo", "copyrightText",
    "currentVersion", "syncCapabilities", "_ssl", "hasStaticData", "hasVersionedData",
    "editorTrackingInfo",
)

# Dropped from every layer definition before it is posted. The first two are
# what the library drops. `relationships` is why the copy is ours: a
# relationship names its related layer by the template's layer *id*, and AGOL
# renumbers layers on the way in, so posted as-is the whole definition is
# refused. `reapply_relationships` puts them back with the ids remapped.
LAYER_STRIPS = ("indexes", "adminLayerInfo", "relationships")


class MasterError(RuntimeError):
    """The master cannot be built, or the copy is not shaped as expected."""


@dataclass(frozen=True)
class IndexOutcome:
    """What happened to one index on one layer."""

    layer: str
    index: str
    status: str
    detail: str = ""


def system_field_names(layer_properties: Any) -> set[str]:
    """Lowercased names of the fields AGOL manages for itself on a layer.

    The object id, the global id, the geometry field under whatever name it
    carries, and the four editor-tracking fields. An index over exactly one of
    these was generated by AGOL, not by anyone on the team.
    """
    names: set[str] = set()

    for key in ("objectIdField", "globalIdField"):
        value = layer_properties.get(key)
        if value:
            names.add(str(value).lower())

    # The geometry field is not reliably called "Shape", so it is found by type.
    for field in layer_properties.get("fields", []) or []:
        if field.get("type") == "esriFieldTypeGeometry":
            names.add(str(field.get("name", "")).lower())

    edit_fields = layer_properties.get("editFieldsInfo") or {}
    for value in edit_fields.values():
        if value:
            names.add(str(value).lower())

    names.discard("")
    return names


def index_fields(index: Any) -> list[str]:
    """The lowercased field names one index covers.

    AGOL reports `fields` as a comma-delimited string; a list is tolerated because
    some portal versions return one.
    """
    raw = index.get("fields", "")
    parts = raw if isinstance(raw, (list, tuple)) else str(raw).split(",")
    return [str(p).strip().lower() for p in parts if str(p).strip()]


def indexable_field_names(layer_properties: Any) -> set[str]:
    """Lowercased names of the fields a layer actually exposes.

    AGOL does *not* list the geometry field in a layer's `fields`, which is how a
    spatial index is recognised even though `esriFieldTypeGeometry` never appears
    there: `..._Shape_sidx` names a field the layer does not expose.
    """
    return {
        str(field.get("name", "")).lower()
        for field in (layer_properties.get("fields", []) or [])
        if field.get("name")
    }


def is_user_defined(index: Any, layer_properties: Any) -> bool:
    """Whether an index is worth reapplying to a copy.

    Two ways to be system-generated, both decided by *fields* rather than names:

    1. The fields are exactly one system field -- the object id, the global id,
       the geometry field, or an editor-tracking field. A composite index is kept
       even when it includes a system field, since nothing AGOL generates on its
       own spans two columns.
    2. Any field is one the layer does not expose. AGOL omits the geometry field
       from `fields`, so this is what catches a spatial index; and an index over a
       field that is not there cannot be reapplied in any case -- AGOL rejects it.

    Rule 2 is skipped for a layer that lists no fields at all, so an unreadable
    definition drops nothing rather than everything.
    """
    fields = index_fields(index)
    if not fields:
        return False

    if len(fields) == 1 and fields[0] in system_field_names(layer_properties):
        return False

    exposed = indexable_field_names(layer_properties)
    if exposed and not all(field in exposed for field in fields):
        return False

    return True


def user_defined_indexes(layer_properties: Any) -> list[dict]:
    """The indexes on one layer that a copy would lose and should get back."""
    return [
        dict(index)
        for index in (layer_properties.get("indexes", []) or [])
        if is_user_defined(index, layer_properties)
    ]


# ---------------------------------------------------------------- the copy


def service_params(template_properties: Any, service_name: str) -> dict[str, Any]:
    """`createService` parameters for the new master, as the library builds them."""
    params = {k: v for k, v in dict(template_properties).items() if k in SERVICE_PARAMS}
    params["name"] = service_name
    params["_ssl"] = False
    return params


def layer_definitions(template_flc: Any) -> dict[str, list[dict[str, Any]]]:
    """Every layer and table of the template, in order, ready to post.

    Deep-copied, so stripping never touches the template."""
    defs: dict[str, list[dict[str, Any]]] = {"layers": [], "tables": []}
    for kind, items in (("layers", template_flc.layers), ("tables", template_flc.tables)):
        for lyr in items:
            payload = copy.deepcopy(dict(lyr.manager.properties))
            for key in LAYER_STRIPS:
                payload.pop(key, None)
            defs[kind].append(payload)
    return defs


def create_empty_service(
    gis: Any, template_flc: Any, service_name: str, *,
    title: str, description: str = "", snippet: str = "", tags: Any = (),
) -> Any:
    """Create the new service with the template's settings and no layers yet.

    Separate from posting the layers so the item is in hand before the call
    that can fail. The library does both in one method and, when the second
    step fails, raises with the item it created lost inside the exception.
    """
    item = gis.content.create_service(
        name=service_name,
        create_params=service_params(template_flc.properties, service_name),
        item_properties={
            "title": title, "description": description, "snippet": snippet,
            "tags": list(tags),
        },
    )
    if item is None:
        raise MasterError(
            f"create_service() returned None for {service_name}. Nothing was created."
        )
    return item


def add_layer_definitions(template_flc: Any, new_flc: Any) -> dict[str, list[dict[str, Any]]]:
    """Post the template's layers and tables to the new service, in one call.

    Returns what was posted. AGOL's refusal is re-raised as a `MasterError`
    carrying its message; the service exists either way.
    """
    defs = layer_definitions(template_flc)
    try:
        new_flc.manager.add_to_definition(defs)
    except Exception as exc:
        raise MasterError(" ".join(str(exc).split())) from exc
    return defs


@dataclass(frozen=True)
class RelationshipOutcome:
    """What happened to one relationship on one layer."""

    layer: str
    relationship: str
    status: str
    detail: str = ""


def reapply_relationships(template_flc: Any, new_flc: Any) -> list[RelationshipOutcome]:
    """Put the template's relationships on the copy, with the layer ids remapped.

    Layers are matched by *name*, which the copy preserves; ids are not. This is
    the same operation `clone_items` performs after it has created a service:
    one service-level `addToDefinition` whose `layers` carry only an `id` and the
    `relationships` to add. Relationships the copy already has are skipped, so a
    re-run repairs rather than duplicates.
    """
    template = list(template_flc.layers) + list(template_flc.tables)
    new = list(new_flc.layers) + list(new_flc.tables)
    template_name_by_id = {l.properties.get("id"): str(l.properties.get("name")) for l in template}
    new_by_name = {str(l.properties.get("name")): l for l in new}

    outcomes: list[RelationshipOutcome] = []
    pending: list[tuple[str, str]] = []
    to_post: dict[Any, list[dict[str, Any]]] = {}

    for t in template:
        wanted = list(t.properties.get("relationships", []) or [])
        if not wanted:
            continue
        name = template_name_by_id[t.properties.get("id")]
        target = new_by_name.get(name)
        if target is None:
            outcomes += [
                RelationshipOutcome(name, str(r.get("name")), FAILED,
                                    f"layer {name!r} is not in the copy")
                for r in wanted
            ]
            continue
        existing = {
            (str(r.get("name")), str(r.get("role")))
            for r in (target.properties.get("relationships", []) or [])
        }
        for r in wanted:
            rel_name = str(r.get("name"))
            if (rel_name, str(r.get("role"))) in existing:
                outcomes.append(RelationshipOutcome(name, rel_name, ALREADY_PRESENT))
                continue
            related_name = template_name_by_id.get(r.get("relatedTableId"))
            related = new_by_name.get(related_name) if related_name else None
            if related is None:
                outcomes.append(RelationshipOutcome(
                    name, rel_name, FAILED,
                    f"its related layer {related_name!r} (template id "
                    f"{r.get('relatedTableId')}) is not in the copy",
                ))
                continue
            remapped = dict(r, relatedTableId=related.properties.get("id"))
            to_post.setdefault(target.properties.get("id"), []).append(remapped)
            pending.append((name, rel_name))

    if to_post:
        payload = {"layers": [{"id": i, "relationships": rels} for i, rels in to_post.items()]}
        try:
            new_flc.manager.add_to_definition(payload)
        except Exception as exc:
            status, detail = _classify_failure(exc)
            outcomes += [RelationshipOutcome(l, r, status, detail) for l, r in pending]
        else:
            outcomes += [RelationshipOutcome(l, r, APPLIED) for l, r in pending]
    return outcomes


# ---------------------------------------------------------------- indexes


def reapply_user_indexes(template_flc: Any, new_flc: Any) -> list[IndexOutcome]:
    """Put the template's user-defined indexes back on the copy."""
    return _reapply(template_flc, new_flc, lambda tpl, _new: user_defined_indexes(tpl))


def reapply_missing_coverage(template_flc: Any, new_flc: Any) -> list[IndexOutcome]:
    """Reapply template indexes covering fields the copy indexes nowhere.

    A second, narrower pass than `reapply_user_indexes`. In practice it finds one
    thing: the GlobalID index. AGOL recreates the editor-tracking indexes and the
    primary key under its own names, and keeps its own spatial index, so those
    are covered -- but the live copy carries nothing over `GlobalID` on any of its
    18 layers, where the template has `FDO_GlobalID` on some and `GlobalID_Index`
    on others. Several template views carry `Sync`, and offline sync keys on
    GlobalID.

    Attempted rather than merely reported, because a rejected batch now retries
    per index: if AGOL declines, that costs one failed call and finally answers
    the question, instead of leaving it open forever.
    """
    return _reapply(template_flc, new_flc, missing_index_coverage)


def _reapply(template_flc: Any, new_flc: Any, select: Any) -> list[IndexOutcome]:
    """Apply the indexes `select` picks, layer by layer.

    Layers are paired by position, which is how the copy was made -- the
    definitions are posted in template order and AGOL numbers them in that
    order. That correspondence is *checked* rather than assumed: applying
    an index to the wrong layer would be a silent wrong answer, so a mismatch
    refuses the whole operation instead of guessing.
    """
    pairs = _paired_layers(template_flc, new_flc)
    outcomes: list[IndexOutcome] = []

    for template_layer, new_layer in pairs:
        name = str(template_layer.properties.get("name", "?"))
        wanted = select(template_layer.properties, new_layer.properties)
        if not wanted:
            continue

        existing = {
            str(i.get("name", "")).lower()
            for i in (new_layer.properties.get("indexes", []) or [])
        }
        to_apply = [i for i in wanted if str(i.get("name", "")).lower() not in existing]
        outcomes += [
            IndexOutcome(name, i["name"], ALREADY_PRESENT)
            for i in wanted
            if i not in to_apply
        ]
        if not to_apply:
            continue

        # One call per layer rather than per index: 18 requests, not 83.
        try:
            new_layer.manager.add_to_definition({"indexes": to_apply})
        except Exception as exc:
            outcomes += _retry_individually(new_layer, name, to_apply, exc)
        else:
            outcomes += [IndexOutcome(name, i["name"], APPLIED) for i in to_apply]

    return outcomes


def _retry_individually(
    layer: Any, layer_name: str, batch: list[dict], batch_error: Exception
) -> list[IndexOutcome]:
    """Salvage the good indexes from a batch AGOL rejected as a whole.

    AGOL fails the entire `add_to_definition` call if any single index in it is
    invalid, so one bad index would otherwise lose every good one on the layer.
    A batch of one has nothing to salvage and is not retried.
    """
    if len(batch) == 1:
        status, detail = _classify_failure(batch_error)
        return [IndexOutcome(layer_name, batch[0]["name"], status, detail)]

    outcomes = []
    for index in batch:
        try:
            layer.manager.add_to_definition({"indexes": [index]})
        except Exception as exc:
            status, detail = _classify_failure(exc)
            outcomes.append(IndexOutcome(layer_name, index["name"], status, detail))
        else:
            outcomes.append(IndexOutcome(layer_name, index["name"], APPLIED))
    return outcomes


def _paired_layers(template_flc: Any, new_flc: Any) -> list[tuple[Any, Any]]:
    """Positional layer/table pairs, refusing to guess if they disagree."""
    template = list(template_flc.layers) + list(template_flc.tables)
    new = list(new_flc.layers) + list(new_flc.tables)

    if len(template) != len(new):
        raise MasterError(
            f"The copy has {len(new)} layer(s) and table(s) but the template has "
            f"{len(template)}. Indexes do not line up; nothing was applied. The copy "
            f"is incomplete -- inspect it before using it."
        )

    mismatched = [
        (t.properties.get("name"), n.properties.get("name"))
        for t, n in zip(template, new)
        if t.properties.get("name") != n.properties.get("name")
    ]
    if mismatched:
        raise MasterError(
            f"Template and copy layers do not line up by position: "
            f"{', '.join(f'{t!r} vs {n!r}' for t, n in mismatched)}. Nothing was "
            f"applied -- an index on the wrong layer is worse than a missing one."
        )
    return list(zip(template, new))


def _classify_failure(exc: Exception) -> tuple[str, str]:
    """A duplicate is the outcome this stage wanted anyway; anything else is a failure."""
    # AGOL returns four lines per rejection; 27 of those buried the summary.
    detail = " ".join(str(exc).split())
    if any(marker in detail.lower() for marker in _DUPLICATE_MARKERS):
        return ALREADY_PRESENT, detail
    return FAILED, detail


# ---------------------------------------------------------------- silent losses

# What a schema copy drops and nothing puts back. Neither of these is repaired
# here -- both are reported, because a named gap can be decided about and a silent
# one cannot. That is the same lesson the indexes taught: the spike measured them
# as "83 missing" for months before anyone classified them.


@dataclass(frozen=True)
class SchemaGap:
    """Something the template has that the copy does not, and nothing restores."""

    layer: str
    kind: str  # "contingent values" | "index"
    detail: str


def index_field_sets(layer_properties: Any) -> set[frozenset[str]]:
    """The field combinations a layer has indexed, ignoring index names."""
    return {
        frozenset(index_fields(index))
        for index in (layer_properties.get("indexes", []) or [])
        if index_fields(index)
    }


def missing_index_coverage(template_properties: Any, new_properties: Any) -> list[dict]:
    """Template indexes covering a field combination the copy indexes nowhere.

    Compared by **fields**, never by name. AGOL recreates most system indexes
    under its own names -- the first live run produced `CreatorIndex` where the
    template had `I13Creator`, and a `PK__TestComp__...` for the template's
    `PK__ZAYO_CHI__...`. Comparing names calls all of those losses; comparing
    fields finds the one that really was lost: the template's `FDO_GlobalID` has
    no counterpart on the copy at all.
    """
    covered = index_field_sets(new_properties)
    return [
        dict(index)
        for index in (template_properties.get("indexes", []) or [])
        if index_fields(index) and frozenset(index_fields(index)) not in covered
    ]


def _contingent_values(layer: Any) -> dict:
    """What `<layer>/contingentValues` returns, or {} when it cannot be read.

    `FeatureLayer.contingent_values` swallows its own errors and returns {}, so
    "unreadable" and "none defined" look the same here. That is why presence is
    also read from the layer definition's `hasContingentValuesDefinition` flag.
    """
    try:
        return getattr(layer, "contingent_values", None) or {}
    except Exception:
        return {}


@dataclass(frozen=True)
class ContingentValues:
    """How much of a contingent-values definition a layer carries."""

    field_groups: int
    contingencies: int

    def __bool__(self) -> bool:
        return self.field_groups > 0 or self.contingencies > 0


def contingent_values_on(layer: Any) -> ContingentValues:
    """Count a layer's field groups and contingencies, from the real response shape.

    The sub-resource has no top-level `contingentValues` key. The definition is
    `contingentValuesDefinition.fieldGroups[]`, each holding `contingencies[]`.
    The first version of this check looked for the key that does not exist and
    so never fired -- the Kinetic master's contingent values went unreported on
    the DeWitt run. The layer definition's own `hasContingentValuesDefinition`
    flag counts as one group when the sub-resource says nothing, so an
    unreadable sub-resource cannot hide a loss the definition admits to.
    """
    raw = _contingent_values(layer)
    definition = raw.get("contingentValuesDefinition") or raw
    groups = list(definition.get("fieldGroups") or [])
    contingencies = sum(len(g.get("contingencies") or []) for g in groups)
    # Older or flatter shapes, just in case: count them rather than miss them.
    contingencies += len(definition.get("contingentValues") or [])
    if not groups and not contingencies:
        try:
            flagged = bool(layer.properties.get("hasContingentValuesDefinition"))
        except Exception:
            flagged = False
        if flagged:
            return ContingentValues(field_groups=1, contingencies=0)
    return ContingentValues(field_groups=len(groups), contingencies=contingencies)


def schema_gaps(template_service: Any, new_service: Any) -> list[SchemaGap]:
    """Everything the copy is missing that this tool does not repair.

    Contingent values live at a separate REST sub-resource, so
    `copy_feature_layer_collection()` -- which builds its payload from each
    layer's admin definition -- cannot carry them, and arcgis ships no writer for
    them at all. Reapplying needs raw REST, which is not built.
    """
    gaps: list[SchemaGap] = []

    for template_layer, new_layer in _paired_layers(template_service, new_service):
        name = str(template_layer.properties.get("name", "?"))

        wanted = contingent_values_on(template_layer)
        if wanted and not contingent_values_on(new_layer):
            gaps.append(SchemaGap(
                name, "contingent values",
                f"{wanted.field_groups} field group(s), {wanted.contingencies} "
                f"contingencies on the template; none on the copy",
            ))

        for index in missing_index_coverage(template_layer.properties, new_layer.properties):
            gaps.append(SchemaGap(
                name, "index",
                f"{index['name']} on {', '.join(index_fields(index))} -- no index on "
                f"the copy covers those fields under any name",
            ))

    return gaps
