"""Stage 1: create the project's master feature service.

The copy itself is settled -- Phase 0b returned `USABLE WITH FIXUPS` with no
critical differences, so `copy_feature_layer_collection()` is the strategy and
there is no publish-from-FGDB fallback. What is left is the one real loss.

`copy_feature_layer_collection()` strips each layer's `indexes` before applying
the definition, so even a perfect copy arrives without them. The spike reported
83 missing index entries across 18 layers, of which 73 are system-generated names
that could never have matched -- SQL Server primary keys with random suffixes,
spatial indexes scoped to the owning account, editor-tracking indexes renumbered
on creation, and GlobalID indexes recreated with the field. Ten are real:
`build_status_Index` on 9 layers and `I25bore_depth` on 1.

`build_status_Index` is the one that matters. `build_status` is the field that
*every* view's definition query filters on, so a master without it makes all
seven views table-scan.

Indexes are classified by their **fields**, never by their names. The system names
carry random suffixes and owner ids, and `I25bore_depth` shows that the `I##`
prefix appears on user indexes too, so the name is evidence of nothing in either
direction.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

# AGOL wording when an index of that name is already there. Tolerated rather than
# fatal: the index existing is the outcome this stage wants either way.
_DUPLICATE_MARKERS = ("duplicate", "already exists", "already in use")

APPLIED = "applied"
ALREADY_PRESENT = "already present"
FAILED = "failed"


class MasterError(RuntimeError):
    """The master cannot be built, or the copy is not shaped as expected."""


@dataclass(frozen=True)
class IndexOutcome:
    """What happened to one index on one layer."""

    layer: str
    index: str
    status: str
    detail: str = ""


def system_field_names(layer_properties: Any) -> set[str]:
    """Lowercased names of the fields AGOL manages for itself on a layer.

    The object id, the global id, the geometry field under whatever name it
    carries, and the four editor-tracking fields. An index over exactly one of
    these was generated by AGOL, not by anyone on the team.
    """
    names: set[str] = set()

    for key in ("objectIdField", "globalIdField"):
        value = layer_properties.get(key)
        if value:
            names.add(str(value).lower())

    # The geometry field is not reliably called "Shape", so it is found by type.
    for field in layer_properties.get("fields", []) or []:
        if field.get("type") == "esriFieldTypeGeometry":
            names.add(str(field.get("name", "")).lower())

    edit_fields = layer_properties.get("editFieldsInfo") or {}
    for value in edit_fields.values():
        if value:
            names.add(str(value).lower())

    names.discard("")
    return names


def index_fields(index: Any) -> list[str]:
    """The lowercased field names one index covers.

    AGOL reports `fields` as a comma-delimited string; a list is tolerated because
    some portal versions return one.
    """
    raw = index.get("fields", "")
    parts = raw if isinstance(raw, (list, tuple)) else str(raw).split(",")
    return [str(p).strip().lower() for p in parts if str(p).strip()]


def is_user_defined(index: Any, system_fields: set[str]) -> bool:
    """Whether an index is worth reapplying to a copy.

    An index is system-generated when its fields are *exactly* one system field.
    A composite index is always kept even if it includes a system field: nothing
    AGOL generates on its own spans two columns.
    """
    fields = index_fields(index)
    if len(fields) == 1 and fields[0] in system_fields:
        return False
    return bool(fields)


def user_defined_indexes(layer_properties: Any) -> list[dict]:
    """The indexes on one layer that a copy would lose and should get back."""
    system = system_field_names(layer_properties)
    return [
        dict(index)
        for index in (layer_properties.get("indexes", []) or [])
        if is_user_defined(index, system)
    ]


def reapply_user_indexes(template_flc: Any, new_flc: Any) -> list[IndexOutcome]:
    """Put the template's user-defined indexes back on the copy.

    Layers are paired by position, which is how the copy was made --
    `copy_feature_layer_collection()` selects by positional index into
    `Item.layers`. That correspondence is *checked* rather than assumed: applying
    an index to the wrong layer would be a silent wrong answer, so a mismatch
    refuses the whole operation instead of guessing.
    """
    pairs = _paired_layers(template_flc, new_flc)
    outcomes: list[IndexOutcome] = []

    for template_layer, new_layer in pairs:
        name = str(template_layer.properties.get("name", "?"))
        wanted = user_defined_indexes(template_layer.properties)
        if not wanted:
            continue

        existing = {
            str(i.get("name", "")).lower()
            for i in (new_layer.properties.get("indexes", []) or [])
        }
        to_apply = [i for i in wanted if str(i.get("name", "")).lower() not in existing]
        outcomes += [
            IndexOutcome(name, i["name"], ALREADY_PRESENT)
            for i in wanted
            if i not in to_apply
        ]
        if not to_apply:
            continue

        # One call per layer rather than per index: 18 requests, not 83.
        try:
            new_layer.manager.add_to_definition({"indexes": to_apply})
        except Exception as exc:
            status, detail = _classify_failure(exc)
            outcomes += [IndexOutcome(name, i["name"], status, detail) for i in to_apply]
        else:
            outcomes += [IndexOutcome(name, i["name"], APPLIED) for i in to_apply]

    return outcomes


def _paired_layers(template_flc: Any, new_flc: Any) -> list[tuple[Any, Any]]:
    """Positional layer/table pairs, refusing to guess if they disagree."""
    template = list(template_flc.layers) + list(template_flc.tables)
    new = list(new_flc.layers) + list(new_flc.tables)

    if len(template) != len(new):
        raise MasterError(
            f"The copy has {len(new)} layer(s) and table(s) but the template has "
            f"{len(template)}. Indexes do not line up; nothing was applied. The copy "
            f"is incomplete -- inspect it before using it."
        )

    mismatched = [
        (t.properties.get("name"), n.properties.get("name"))
        for t, n in zip(template, new)
        if t.properties.get("name") != n.properties.get("name")
    ]
    if mismatched:
        raise MasterError(
            f"Template and copy layers do not line up by position: "
            f"{', '.join(f'{t!r} vs {n!r}' for t, n in mismatched)}. Nothing was "
            f"applied -- an index on the wrong layer is worse than a missing one."
        )
    return list(zip(template, new))


def _classify_failure(exc: Exception) -> tuple[str, str]:
    """A duplicate is the outcome this stage wanted anyway; anything else is a failure."""
    detail = str(exc)
    if any(marker in detail.lower() for marker in _DUPLICATE_MARKERS):
        return ALREADY_PRESENT, detail
    return FAILED, detail
