"""Stage 1: create the project's master feature service.

The copy itself is settled -- Phase 0b returned `USABLE WITH FIXUPS` with no
critical differences, so `copy_feature_layer_collection()` is the strategy and
there is no publish-from-FGDB fallback. What is left is the one real loss.

`copy_feature_layer_collection()` strips each layer's `indexes` before applying
the definition, so even a perfect copy arrives without them. The spike reported
83 missing index entries across 18 layers, of which 73 are system-generated names
that could never have matched -- SQL Server primary keys with random suffixes,
spatial indexes scoped to the owning account, editor-tracking indexes renumbered
on creation, and GlobalID indexes recreated with the field. Ten are real:
`build_status_Index` on 9 layers and `I25bore_depth` on 1.

The first live run confirmed the renumbering rather than merely predicting it.
`copy_feature_layer_collection()` deletes `indexes` from every layer definition
before posting it, and this module drops every single-system-field index, so the
creation request carried *no* GlobalID or editor-tracking index at all -- yet the
copy has them, under names without the template's `I25` prefix. ArcGIS Online
creates them itself from the GlobalID field and the copied editor-tracking
settings. Nothing names an index but the query planner, so nothing is lost.

`build_status_Index` is the one that matters. `build_status` is the field that
*every* view's definition query filters on, so a master without it makes all
seven views table-scan.

Indexes are classified by their **fields**, never by their names. The system names
carry random suffixes and owner ids, and `I25bore_depth` shows that the `I##`
prefix appears on user indexes too, so the name is evidence of nothing in either
direction.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

# AGOL wording when an index of that name is already there. Tolerated rather than
# fatal: the index existing is the outcome this stage wants either way.
_DUPLICATE_MARKERS = ("duplicate", "already exists", "already in use")

APPLIED = "applied"
ALREADY_PRESENT = "already present"
FAILED = "failed"


class MasterError(RuntimeError):
    """The master cannot be built, or the copy is not shaped as expected."""


@dataclass(frozen=True)
class IndexOutcome:
    """What happened to one index on one layer."""

    layer: str
    index: str
    status: str
    detail: str = ""


def system_field_names(layer_properties: Any) -> set[str]:
    """Lowercased names of the fields AGOL manages for itself on a layer.

    The object id, the global id, the geometry field under whatever name it
    carries, and the four editor-tracking fields. An index over exactly one of
    these was generated by AGOL, not by anyone on the team.
    """
    names: set[str] = set()

    for key in ("objectIdField", "globalIdField"):
        value = layer_properties.get(key)
        if value:
            names.add(str(value).lower())

    # The geometry field is not reliably called "Shape", so it is found by type.
    for field in layer_properties.get("fields", []) or []:
        if field.get("type") == "esriFieldTypeGeometry":
            names.add(str(field.get("name", "")).lower())

    edit_fields = layer_properties.get("editFieldsInfo") or {}
    for value in edit_fields.values():
        if value:
            names.add(str(value).lower())

    names.discard("")
    return names


def index_fields(index: Any) -> list[str]:
    """The lowercased field names one index covers.

    AGOL reports `fields` as a comma-delimited string; a list is tolerated because
    some portal versions return one.
    """
    raw = index.get("fields", "")
    parts = raw if isinstance(raw, (list, tuple)) else str(raw).split(",")
    return [str(p).strip().lower() for p in parts if str(p).strip()]


def indexable_field_names(layer_properties: Any) -> set[str]:
    """Lowercased names of the fields a layer actually exposes.

    AGOL does *not* list the geometry field in a layer's `fields`, which is how a
    spatial index is recognised even though `esriFieldTypeGeometry` never appears
    there: `..._Shape_sidx` names a field the layer does not expose.
    """
    return {
        str(field.get("name", "")).lower()
        for field in (layer_properties.get("fields", []) or [])
        if field.get("name")
    }


def is_user_defined(index: Any, layer_properties: Any) -> bool:
    """Whether an index is worth reapplying to a copy.

    Two ways to be system-generated, both decided by *fields* rather than names:

    1. The fields are exactly one system field -- the object id, the global id,
       the geometry field, or an editor-tracking field. A composite index is kept
       even when it includes a system field, since nothing AGOL generates on its
       own spans two columns.
    2. Any field is one the layer does not expose. AGOL omits the geometry field
       from `fields`, so this is what catches a spatial index; and an index over a
       field that is not there cannot be reapplied in any case -- AGOL rejects it.

    Rule 2 is skipped for a layer that lists no fields at all, so an unreadable
    definition drops nothing rather than everything.
    """
    fields = index_fields(index)
    if not fields:
        return False

    if len(fields) == 1 and fields[0] in system_field_names(layer_properties):
        return False

    exposed = indexable_field_names(layer_properties)
    if exposed and not all(field in exposed for field in fields):
        return False

    return True


def user_defined_indexes(layer_properties: Any) -> list[dict]:
    """The indexes on one layer that a copy would lose and should get back."""
    return [
        dict(index)
        for index in (layer_properties.get("indexes", []) or [])
        if is_user_defined(index, layer_properties)
    ]


def reapply_user_indexes(template_flc: Any, new_flc: Any) -> list[IndexOutcome]:
    """Put the template's user-defined indexes back on the copy."""
    return _reapply(template_flc, new_flc, lambda tpl, _new: user_defined_indexes(tpl))


def reapply_missing_coverage(template_flc: Any, new_flc: Any) -> list[IndexOutcome]:
    """Reapply template indexes covering fields the copy indexes nowhere.

    A second, narrower pass than `reapply_user_indexes`. In practice it finds one
    thing: the GlobalID index. AGOL recreates the editor-tracking indexes and the
    primary key under its own names, and keeps its own spatial index, so those
    are covered -- but the live copy carries nothing over `GlobalID` on any of its
    18 layers, where the template has `FDO_GlobalID` on some and `GlobalID_Index`
    on others. Several template views carry `Sync`, and offline sync keys on
    GlobalID.

    Attempted rather than merely reported, because a rejected batch now retries
    per index: if AGOL declines, that costs one failed call and finally answers
    the question, instead of leaving it open forever.
    """
    return _reapply(template_flc, new_flc, missing_index_coverage)


def _reapply(template_flc: Any, new_flc: Any, select: Any) -> list[IndexOutcome]:
    """Apply the indexes `select` picks, layer by layer.

    Layers are paired by position, which is how the copy was made --
    `copy_feature_layer_collection()` selects by positional index into
    `Item.layers`. That correspondence is *checked* rather than assumed: applying
    an index to the wrong layer would be a silent wrong answer, so a mismatch
    refuses the whole operation instead of guessing.
    """
    pairs = _paired_layers(template_flc, new_flc)
    outcomes: list[IndexOutcome] = []

    for template_layer, new_layer in pairs:
        name = str(template_layer.properties.get("name", "?"))
        wanted = select(template_layer.properties, new_layer.properties)
        if not wanted:
            continue

        existing = {
            str(i.get("name", "")).lower()
            for i in (new_layer.properties.get("indexes", []) or [])
        }
        to_apply = [i for i in wanted if str(i.get("name", "")).lower() not in existing]
        outcomes += [
            IndexOutcome(name, i["name"], ALREADY_PRESENT)
            for i in wanted
            if i not in to_apply
        ]
        if not to_apply:
            continue

        # One call per layer rather than per index: 18 requests, not 83.
        try:
            new_layer.manager.add_to_definition({"indexes": to_apply})
        except Exception as exc:
            outcomes += _retry_individually(new_layer, name, to_apply, exc)
        else:
            outcomes += [IndexOutcome(name, i["name"], APPLIED) for i in to_apply]

    return outcomes


def _retry_individually(
    layer: Any, layer_name: str, batch: list[dict], batch_error: Exception
) -> list[IndexOutcome]:
    """Salvage the good indexes from a batch AGOL rejected as a whole.

    AGOL fails the entire `add_to_definition` call if any single index in it is
    invalid, so one bad index would otherwise lose every good one on the layer.
    A batch of one has nothing to salvage and is not retried.
    """
    if len(batch) == 1:
        status, detail = _classify_failure(batch_error)
        return [IndexOutcome(layer_name, batch[0]["name"], status, detail)]

    outcomes = []
    for index in batch:
        try:
            layer.manager.add_to_definition({"indexes": [index]})
        except Exception as exc:
            status, detail = _classify_failure(exc)
            outcomes.append(IndexOutcome(layer_name, index["name"], status, detail))
        else:
            outcomes.append(IndexOutcome(layer_name, index["name"], APPLIED))
    return outcomes


def _paired_layers(template_flc: Any, new_flc: Any) -> list[tuple[Any, Any]]:
    """Positional layer/table pairs, refusing to guess if they disagree."""
    template = list(template_flc.layers) + list(template_flc.tables)
    new = list(new_flc.layers) + list(new_flc.tables)

    if len(template) != len(new):
        raise MasterError(
            f"The copy has {len(new)} layer(s) and table(s) but the template has "
            f"{len(template)}. Indexes do not line up; nothing was applied. The copy "
            f"is incomplete -- inspect it before using it."
        )

    mismatched = [
        (t.properties.get("name"), n.properties.get("name"))
        for t, n in zip(template, new)
        if t.properties.get("name") != n.properties.get("name")
    ]
    if mismatched:
        raise MasterError(
            f"Template and copy layers do not line up by position: "
            f"{', '.join(f'{t!r} vs {n!r}' for t, n in mismatched)}. Nothing was "
            f"applied -- an index on the wrong layer is worse than a missing one."
        )
    return list(zip(template, new))


def _classify_failure(exc: Exception) -> tuple[str, str]:
    """A duplicate is the outcome this stage wanted anyway; anything else is a failure."""
    # AGOL returns four lines per rejection; 27 of those buried the summary.
    detail = " ".join(str(exc).split())
    if any(marker in detail.lower() for marker in _DUPLICATE_MARKERS):
        return ALREADY_PRESENT, detail
    return FAILED, detail


# ---------------------------------------------------------------- silent losses

# What a schema copy drops and nothing puts back. Neither of these is repaired
# here -- both are reported, because a named gap can be decided about and a silent
# one cannot. That is the same lesson the indexes taught: the spike measured them
# as "83 missing" for months before anyone classified them.


@dataclass(frozen=True)
class SchemaGap:
    """Something the template has that the copy does not, and nothing restores."""

    layer: str
    kind: str  # "contingent values" | "index"
    detail: str


def index_field_sets(layer_properties: Any) -> set[frozenset[str]]:
    """The field combinations a layer has indexed, ignoring index names."""
    return {
        frozenset(index_fields(index))
        for index in (layer_properties.get("indexes", []) or [])
        if index_fields(index)
    }


def missing_index_coverage(template_properties: Any, new_properties: Any) -> list[dict]:
    """Template indexes covering a field combination the copy indexes nowhere.

    Compared by **fields**, never by name. AGOL recreates most system indexes
    under its own names -- the first live run produced `CreatorIndex` where the
    template had `I13Creator`, and a `PK__TestComp__...` for the template's
    `PK__ZAYO_CHI__...`. Comparing names calls all of those losses; comparing
    fields finds the one that really was lost: the template's `FDO_GlobalID` has
    no counterpart on the copy at all.
    """
    covered = index_field_sets(new_properties)
    return [
        dict(index)
        for index in (template_properties.get("indexes", []) or [])
        if index_fields(index) and frozenset(index_fields(index)) not in covered
    ]


def _contingent_values(layer: Any) -> dict:
    """A layer's contingent values, or {} when there are none or they cannot be read.

    `FeatureLayer.contingent_values` swallows its own errors and returns {}, so
    "unreadable" and "none defined" are indistinguishable. Both are treated as
    "nothing to report" rather than as a loss -- claiming a loss we cannot see is
    worse than staying quiet about one we cannot confirm.
    """
    try:
        return getattr(layer, "contingent_values", None) or {}
    except Exception:
        return {}


def schema_gaps(template_service: Any, new_service: Any) -> list[SchemaGap]:
    """Everything the copy is missing that this tool does not repair.

    Contingent values live at a separate REST sub-resource, so
    `copy_feature_layer_collection()` -- which builds its payload from each
    layer's admin definition -- cannot carry them, and arcgis ships no writer for
    them at all. Reapplying needs raw REST, which is not built.
    """
    gaps: list[SchemaGap] = []

    for template_layer, new_layer in _paired_layers(template_service, new_service):
        name = str(template_layer.properties.get("name", "?"))

        wanted = _contingent_values(template_layer).get("contingentValues")
        if wanted and not _contingent_values(new_layer).get("contingentValues"):
            gaps.append(SchemaGap(
                name, "contingent values",
                f"{len(wanted)} defined on the template, none on the copy",
            ))

        for index in missing_index_coverage(template_layer.properties, new_layer.properties):
            gaps.append(SchemaGap(
                name, "index",
                f"{index['name']} on {', '.join(index_fields(index))} -- no index on "
                f"the copy covers those fields under any name",
            ))

    return gaps
